version: '3.8'

services:
  stringz:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - DOCKER_CONTAINER=1
    restart: unless-stopped
